### ISSUE TITLE
Is there a version of cuCIM for (anaconda) Python on windows?[QST]

### ISSUE THREAD

**Issue by yliu88au** [rapidsai/cucim#270]
**What is your question?**

**Comment by yliu88au** [comment]
I have followed the installation instruction and installed cuCIM on (anaconda) Python/Ubuntu system, but fail to find any way to install cuCim for (anaconda) Python/Windows.

**Comment by grlee77** [comment]
Please see https://github.com/rapidsai/cucim/issues/86 for some prior discussion of this. If you need only the `cucim.skimage` component, there is a description of an unofficial way to install that from source as a pure Python package [here](https://github.com/rapidsai/cucim/issues/64#issuecomment-878535597). Otherwise, I think using Windows Subsystem for Linux (WSL) is the only way it can currently be done.

**Comment by yliu88au** [comment]
Thank you very much for your help. Indeed, I am currently only interested in `cucim.skimage`  component. I have followed the instruction in #86 and installed current version of the pure Python bits by:
`pip install -e "git+https://github.com/rapidsai/cucim.git@v22.04.00#egg=cucim&subdirectory=python/cucim" scipy scikit-image`
It seems working.

**Comment by gigony** [comment]
Closing this. Windows support-relased questions are discussed in https://github.com/rapidsai/cucim/issues/454#issuecomment-1331244039

**Comment by gigony** [comment]
Need `egg=cucim-cu12` instead of `egg=cucim` now:

```
pip install -e "git+https://github.com/rapidsai/cucim.git@v24.10.00#egg=cucim-cu12&subdirectory=python/cucim" scipy scikit-image
```
