### ISSUE TITLE
[DOC] out-of-date docstring for `map_coordinates`

### ISSUE THREAD

**Issue by wyli** [rapidsai/cucim#387]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/rapidsai/cucim/blob/e155e320ab4bbe1e37f7d35dbd3870ccd8beed64/python/cucim/src/cucim/skimage/_vendored/_ndimage_interpolation.py#L278-L279

the docstring says `prefilter=True` is not implemented, but seems it's implemented
via https://github.com/cupy/cupy/pull/4402

could you please help confirm? cc @grlee77

**Comment by grlee77** [comment]
Yes, it is implemented and the docstring just needs to be updated upstream in CuPy (it is still outdated [there](https://github.com/cupy/cupy/blob/ca8c6e3d9ad53d34a26b684cf5388a9f17d17007/cupyx/scipy/ndimage/_interpolation.py#L279-L280)). If you want to make a CuPy to fix it that would be great! This `_vendored` folder is here because we are using some slight modifications to CuPy ndimage or features that weren't yet in our minimum supported release, but we are not publicly exporting this module so the fix should really be upstream.

**Comment by grlee77** [comment]
Thanks for reporting the issue @wyli!

**Comment by wyli** [comment]
thanks @grlee77 , I create a PR as you suggested.
