### ISSUE TITLE
[BUG] cucim.skimage.util.img_as_float returns np.float32 while skimage.util.img_as_float returns np.float64

### ISSUE THREAD

**Issue by monzelr** [rapidsai/cucim#417]
**Describe the bug**
`cucim.skimage.util.img_as_float` returns `np.float32` while `skimage.util.img_as_float` returns `np.float64` if the input image is from dtype `np.uint16`

**Steps/Code to reproduce bug**
```python
import sys

import skimage
import cucim
import numpy as np
import cupy as cp

print("Python version: ", sys.version)
print()

print("skimage version: ", skimage.__version__)
print("cucim version: ", cucim.__version__)  # branch-22.10
print()

_image = np.array([0, 1, 2, 3, 4], dtype=np.uint16)
print("skimage.util.img_as_float:")
print(skimage.util.img_as_float(_image).dtype)
print()

_cp_image = cp.asarray(_image, dtype=np.uint16)
print("cucim.skimage.util.img_as_float:")
print(cucim.skimage.util.img_as_float(_cp_image).dtype)
print()
```

**Expected behavior**
Expected the same output between `cucim.skimage.util.img_as_float` and `skimage.util.img_as_float`.

**Environment details (please complete the following information):**
Output of python code:
```
 Python version:  3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]

skimage version:  0.19.3
cucim version:  0+untagged.253.g649b404.dirty

skimage.util.img_as_float:
float64

cucim.skimage.util.img_as_float:
float32

```

**Additional context**
In `skimage`...
What I see in the `skimage.util.img_as_float` [function](https://github.com/scikit-image/scikit-image/blob/533a5b5c0852b38890d63c348117aba8055b3995/skimage/util/dtype.py#L442) is a `numpy.floating` as input for `_convert` - however, `numpy.floating` is a base class.

In `cucim`...
The `cucim.skimage.util.img_as_float` [function](https://github.com/rapidsai/cucim/blob/92fa67e8b263035076891c73b68981df7999cf29/python/cucim/src/cucim/skimage/util/dtype.py#L443) is using `_supported_float_type` function, which returns `np.float32`.

\
Maybe the `img_as_float` returns `numpy.float32` due to performance reason, if yes it should be noted in the documentation.

Issue have been detected during PR #413.

**Comment by grlee77** [comment]
Hi @monzelr, thanks for reporting this.

This was an intentional change we made in cuCIM to use `float32` over `float64` for performance reasons when it is safe to do so. `int8`, `uint8`, `int16` and `uint16` will get converted to float32 while larger integer types will still become `float64`.

It is possible we will also change scikit-image to match this behavior in the future. See https://github.com/scikit-image/scikit-image/issues/6310

Given that this is expected behavior I will close the issue, but feel free to continue the discussion here
