### ISSUE TITLE
cuda 10.x support

### ISSUE THREAD

**Issue by chrisroat** [rapidsai/cucim#44]
Is cuda 10.x support feasible or planned?

**Comment by quasiben** [comment]
Unfortunately, no.    cuCIM depends on 11.X features -- @gigony is the best person to explain where those features are used.

**Comment by gigony** [comment]
Hi @chrisroat,

To support GDS feature in cuCIM, CUDA version >= 11.x is needed (though we currently disabled GDS feature for now and would enable it again in the future) and we currently release conda packages with CUDA 11.x only

However, since cuCIM's IO package (cucim.CuImage/ cucim.clara.xxx) works independently with cuCIM's CuPy-based scikit-image API (cucim.skimage), I think you can install and use only `cucim.skimage` (previously https://github.com/mritools/cupyimg ) package through the following command using pip:

```bash
# Replace cupy-cuda10X with corresponding version name such as `cupy-cuda102` available from https://cupy.dev/
pip install --upgrade scipy scikit-image cupy-cuda10X cucim
```

Please help let us know your use cases with cuCIM!

**Comment by chrisroat** [comment]
Thanks!  The github README.md explicitly indicates cuda 11 is needed.  I have another package stuck on cuda 10 for the near future, so want to stick with 10 for a while.   I did a small test with your cuda 10 suggestion with cucim, and things seem fine.  I will try some larger tests in our full stack before we make the full switch from cupyimg (which we currently use) to cucim.

Our use case is GPU-accelerated skimage rigid registration of neuroscience image processing.   The rest of our cupyimg use is in scipy, which seems to be absorbed into mainline cupy.  We also have some other existing cupy based routines, as well.

I will close this because you've provided a lot of helpful information and I should be good to go.

**Comment by chrisroat** [comment]
I am finding in my cuda 10.1 environment, something seems to still want to pull in 11.0, which isn't present:

```
    from cucim.skimage import registration
../../.local/share/virtualenvs/starmap-T47byR32/lib/python3.8/site-packages/cucim/__init__.py:34: in <module>
    from .clara import CuImage
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    import os
    
    from . import cli
    from . import converter
    # import hidden methods
>   from ._cucim import CuImage
E   ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

../../.local/share/virtualenvs/starmap-T47byR32/lib/python3.8/site-packages/cucim/clara/__init__.py:21: ImportError
```

When removing cucim with pip, I see a cudart 11.0 so file being removed:

```
/home/croat/.local/share/virtualenvs/starmap-T47byR32/lib/python3.8/site-packages/cucim-0.19.0.dist-info/*
    /home/croat/.local/share/virtualenvs/starmap-T47byR32/lib/python3.8/site-packages/cucim.libs/libcudart-3f3c6934.so.11.0.221
    /home/croat/.local/share/virtualenvs/starmap-T47byR32/lib/python3.8/site-packages/cucim.libs/libz-d8a329de.so.1.2.7
```

Does this indicate that, short of rebuilding some pieces, it is tied to 11.+?

**Comment by gigony** [comment]
Hi @chrisroat 

I forgot and ignored the fact that `cucim/__init__.py` would be also imported as well as `cucim/skimage/__init__.py` when executing `import cucim.skimage`.
Yes, the current version always import `cucim.clara` package so it has dependencies to CUDA 11.+.
I am sorry for the confusion.

Let me push a pre-release version of the PyPI package soon that removes the dependency so that you can use it for now.

And, in the next release, I would make sure that it doesn't depend on CUDA 11.x+ when only `cucim.skimage` package is needed.

**Comment by chrisroat** [comment]
Yes, I have run both our unit tests and deployed it on our Docker images.  Both are doing great!

Much appreciated!
