### ISSUE TITLE
Is `cucim.code-workspace` still used?

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cucim#706]
Just wanted to confirm that we are still using `cucim.code-workspace`. If not, maybe we can drop it?

**Comment by jakirkham** [comment]
@gigony do you know?

**Comment by gigony** [comment]
Hi @jakirkham 
I use the VSCode workspace setup when I develop CPP module.
It's been a while since I update C++ code in cuCIM and I may need to refactor whole build pipeline someday (and support rapids-cmake: https://github.com/rapidsai/cucim/issues/627) but I see it (`code cucim.code-workspace`) is still working.

![image](https://github.com/rapidsai/cucim/assets/1928522/8123b263-9641-4f83-bf4e-1756bfe8449c)
