### ISSUE TITLE
[QST] Is it available for OS Win?

### ISSUE THREAD

**Issue by otakarkuchar** [rapidsai/cucim#86]
I have tried install in Conda prompt:
pip install cucim
ERROR: Could not find a version that satisfies the requirement cucim (from versions: none)
ERROR: No matching distribution found for cucim

Is it available for OS Win or what I have made done wrong? Thank you for asist

**Comment by quasiben** [comment]
You should be able to install via PIP and it's possible it works with Windows.  If you run into trouble you could try running [RAPIDS on WSL](https://medium.com/rapids-ai/running-rapids-on-microsoft-windows-10-using-wsl-2-the-windows-subsystem-for-linux-c5cbb2c56e04), which may provide an alternative path forward .   We just released [21.08 on pypi yesterday](https://pypi.org/project/cucim/)

**Comment by haesleinhuepf** [comment]
> You should be able to install via PIP and it's possible it works with Windows

That sounds fantastic! However, when I run pip, it says:
```
 C:\structure\code\pyclesperanto_prototype>pip install cucim==21.08
ERROR: Could not find a version that satisfies the requirement cucim==21.08 (from versions: none)
ERROR: No matching distribution found for cucim==21.08
```

Any ideas how to debug this?

Btw. WSL is no way forward in my usecase unfortunately...

**Comment by otakarkuchar** [comment]
> > You should be able to install via PIP and it's possible it works with Windows
> 
> That sounds fantastic! However, when I run pip, it says:
> 
> ```
>  C:\structure\code\pyclesperanto_prototype>pip install cucim==21.08
> ERROR: Could not find a version that satisfies the requirement cucim==21.08 (from versions: none)
> ERROR: No matching distribution found for cucim==21.08
> ```
> 
> Any ideas how to debug this?
> 
> Btw. WSL is no way forward in my usecase unfortunately...

I have the same problem :(

**Comment by quasiben** [comment]
On PyPi,  I believe the version is `21.8.1`.  Running `pip install cucim` should be the latest version

**Comment by otakarkuchar** [comment]
> PyPi

**Comment by otakarkuchar** [comment]
> On PyPi, I believe the version is `21.8.1`. Running `pip install cucim` should be the latest version

When I did:
pip install PyPi
Successfully installed PyPi-2.1

pip install cucim
ERROR: Could not find a version that satisfies the requirement cucim (from versions: none)
ERROR: No matching distribution found for cucim

Can you please describe the installation procedure steps? thank you so much

**Comment by gigony** [comment]
Hi @otakarkuchar,

Since the image loader part(cucim.clara) of cuCIM supports (and assumed) Linux environment only, the current PyPI package (wheel[.whl] file) doesn't support Windows (although it supports WSL) for now.

Could you tell us your use case with cuCIM? If you only needs image processing API based on CuPy (cucim.skimage package), I think it is possible that we may be able to release a PyPI package for Windows, having only `cucim.skimage` module in the next release.

**Comment by otakarkuchar** [comment]
> Hi @otakarkuchar,
> 
> Since the image loader part(`cucim.clara` module) of cuCIM supports (and assumed) Linux environment only, the current PyPI package (wheel[.whl] file) doesn't support Windows (although it supports WSL) for now.
> 
> Could you tell us your use case with cuCIM? If you only needs image processing API based on CuPy (`cucim.skimage` module which is pure python code), I think it is possible that we may be able to release a PyPI package for Windows, having only `cucim.skimage` module in the next release.

Yes, my case is only image processing on 3D datasets. If you do that, it will be great! I am looking forward to try cucim.skimage library! ... Thank you guys!

**Comment by haesleinhuepf** [comment]
> I think it is possible that we may be able to release a PyPI package for Windows, having only `cucim.skimage` module in the next release.

Oh that would be great indeed! ❤️

**Comment by grlee77** [comment]
Although not officially documented, as long as you have CuPy >= 9.0 installed you should be able to install `cucim.skimage` standalone (without the need to compile any code) as described here: https://github.com/rapidsai/cucim/issues/64#issuecomment-878535597

**Comment by haesleinhuepf** [comment]
> Although not officially documented, as long as you have CuPy >= 9.0 installed you should be able to install `cucim.skimage` standalone (without the need to compile any code) as described here: [#64 (comment)](https://github.com/rapidsai/cucim/issues/64#issuecomment-878535597)

That's great! Are there any plans for making an independent package out of that? Would be great to `pip install cucim-scikit-image`. ;-)

**Comment by grlee77** [comment]
> Are there any plans for making an independent package out of that?

I will try to discuss with @gigony and the team next week about what potential options for this might be across pip and conda installs. I suppose we could make a `cucim_skimage` conda package that installed as described in my prior comment as long as we mark that package in conflict with the main `cucim` one so that users can only install one or the other, but not both. A second option is splitting the `cucim` package into separate `cucim.clara` and `cucim.skimage` namespace packages, but I would like to avoid that if possible.

**Comment by iperov** [comment]
@gigony 

> Instruction to install cuCIM on Windows
After cupy is installed

then why need cuCIM if CuPy should be installed?

**Comment by gigony** [comment]
Hello @iperov 

Thanks for the question!

cuCIM's scikit-image API (image processing module based on CuPy) comes from @grlee77 (co-author of cuCIM)'s project named [`cupyimg`](https://github.com/mritools/cupyimg) which extends CuPy with additional functions for image/signal processing.
With cuCIM, you can use [other image processing algorithms](https://docs.rapids.ai/api/cucim/stable/api.html#skimage-submodules) that are not in CuPy's [`cupyx.scipy.ndimage`](https://docs.cupy.dev/en/stable/reference/ndimage.html).

Since `pip install cucim` would build&install from the source which takes a long time, CuPy(https://cupy.dev/) provides pre-built packages for each CUDA Toolkit version(such as  `cupy-cuda110`).
In addition, users may want to use only data loader part (`cucim.CuImage` or `cucim.clara` which doesn't require CuPy) or just `clara.skimage` module, we made `cupy` not a mandatory package to install (please see [setup.py](https://github.com/rapidsai/cucim/blob/branch-21.10/python/cucim/setup.py#L86)).

When `import cucim` is executed, it first tries to `import cupy` and  `import cupy.Image` (requires CUDA >= 11.0) optionally (please see [`__init__.py`](https://github.com/rapidsai/cucim/blob/branch-21.10/python/cucim/src/cucim/__init__.py#L34).

Please let me know if you have other questions.
Thank you!

**Comment by iperov** [comment]
I don't like such a Game of Dependencies.
I want to see cuCIM lib that will implement all cupy + gpu image processing only with cuda lib, without dependencies.
Notify me when it happens.

**Comment by gigony** [comment]
Thanks @iperov for the feedback!
We have a plan to implement some image processing algorithms in C++ that don't depend on CuPy but implementing all the image processing algorithms are not feasible and would take much time to implement.
For this reason, we are also thinking about providing existing GPU-accelerated image processing implementations from 3rdparty libraries as a plugin.
[Arrayfire](https://arrayfire.com/) is one of the candidates.
Please take a look at the library (it has a [python wrapper](https://pypi.org/project/arrayfire/), [instruction](https://github.com/arrayfire/arrayfire-python/wiki)) and it would be great if you could share your experience with it in terms of usability/functionality that is missing.
Thank you!

**Comment by gigony** [comment]
Closing this issue.
Please feel free to reopen if you have any other questions.
Thank you!
